#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLVanBan.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLVanBan")]
	public partial class DataClassesQLVanBanDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDanhMuc(DanhMuc instance);
    partial void UpdateDanhMuc(DanhMuc instance);
    partial void DeleteDanhMuc(DanhMuc instance);
    partial void InsertFileVanBan(FileVanBan instance);
    partial void UpdateFileVanBan(FileVanBan instance);
    partial void DeleteFileVanBan(FileVanBan instance);
    partial void InsertVanBan(VanBan instance);
    partial void UpdateVanBan(VanBan instance);
    partial void DeleteVanBan(VanBan instance);
    #endregion
		
		public DataClassesQLVanBanDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLVanBanConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesQLVanBanDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesQLVanBanDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesQLVanBanDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesQLVanBanDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DanhMuc> DanhMucs
		{
			get
			{
				return this.GetTable<DanhMuc>();
			}
		}
		
		public System.Data.Linq.Table<FileVanBan> FileVanBans
		{
			get
			{
				return this.GetTable<FileVanBan>();
			}
		}
		
		public System.Data.Linq.Table<VanBan> VanBans
		{
			get
			{
				return this.GetTable<VanBan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhMuc")]
	public partial class DanhMuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DanhMucID;
		
		private string _TenDanhMuc;
		
		private string _TenDanhMucKhongDau;
		
		private System.Nullable<int> _LFT;
		
		private System.Nullable<int> _RGT;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<System.DateTime> _UpdatedDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDanhMucIDChanging(int value);
    partial void OnDanhMucIDChanged();
    partial void OnTenDanhMucChanging(string value);
    partial void OnTenDanhMucChanged();
    partial void OnTenDanhMucKhongDauChanging(string value);
    partial void OnTenDanhMucKhongDauChanged();
    partial void OnLFTChanging(System.Nullable<int> value);
    partial void OnLFTChanged();
    partial void OnRGTChanging(System.Nullable<int> value);
    partial void OnRGTChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnUpdatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedDateChanged();
    #endregion
		
		public DanhMuc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhMucID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DanhMucID
		{
			get
			{
				return this._DanhMucID;
			}
			set
			{
				if ((this._DanhMucID != value))
				{
					this.OnDanhMucIDChanging(value);
					this.SendPropertyChanging();
					this._DanhMucID = value;
					this.SendPropertyChanged("DanhMucID");
					this.OnDanhMucIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDanhMuc", DbType="NVarChar(1000)")]
		public string TenDanhMuc
		{
			get
			{
				return this._TenDanhMuc;
			}
			set
			{
				if ((this._TenDanhMuc != value))
				{
					this.OnTenDanhMucChanging(value);
					this.SendPropertyChanging();
					this._TenDanhMuc = value;
					this.SendPropertyChanged("TenDanhMuc");
					this.OnTenDanhMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDanhMucKhongDau", DbType="NVarChar(1000)")]
		public string TenDanhMucKhongDau
		{
			get
			{
				return this._TenDanhMucKhongDau;
			}
			set
			{
				if ((this._TenDanhMucKhongDau != value))
				{
					this.OnTenDanhMucKhongDauChanging(value);
					this.SendPropertyChanging();
					this._TenDanhMucKhongDau = value;
					this.SendPropertyChanged("TenDanhMucKhongDau");
					this.OnTenDanhMucKhongDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LFT", DbType="Int")]
		public System.Nullable<int> LFT
		{
			get
			{
				return this._LFT;
			}
			set
			{
				if ((this._LFT != value))
				{
					this.OnLFTChanging(value);
					this.SendPropertyChanging();
					this._LFT = value;
					this.SendPropertyChanged("LFT");
					this.OnLFTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RGT", DbType="Int")]
		public System.Nullable<int> RGT
		{
			get
			{
				return this._RGT;
			}
			set
			{
				if ((this._RGT != value))
				{
					this.OnRGTChanging(value);
					this.SendPropertyChanging();
					this._RGT = value;
					this.SendPropertyChanged("RGT");
					this.OnRGTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedDate
		{
			get
			{
				return this._UpdatedDate;
			}
			set
			{
				if ((this._UpdatedDate != value))
				{
					this.OnUpdatedDateChanging(value);
					this.SendPropertyChanging();
					this._UpdatedDate = value;
					this.SendPropertyChanged("UpdatedDate");
					this.OnUpdatedDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FileVanBan")]
	public partial class FileVanBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _FileID;
		
		private int _VanBanID;
		
		private string _FileName;
		
		private string _FileType;
		
		private System.Nullable<long> _FileSize;
		
		private string _ClientFileName;
		
		private string _ServerFileName;
		
		private System.Nullable<System.DateTime> _UpdatedDate;
		
		private string _UpdatedUser;
		
		private string _MapPath;
		
		private System.Nullable<int> _PageNumber;
		
		private System.Nullable<int> _DownloadCount;
		
		private EntityRef<VanBan> _VanBan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFileIDChanging(long value);
    partial void OnFileIDChanged();
    partial void OnVanBanIDChanging(int value);
    partial void OnVanBanIDChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnFileTypeChanging(string value);
    partial void OnFileTypeChanged();
    partial void OnFileSizeChanging(System.Nullable<long> value);
    partial void OnFileSizeChanged();
    partial void OnClientFileNameChanging(string value);
    partial void OnClientFileNameChanged();
    partial void OnServerFileNameChanging(string value);
    partial void OnServerFileNameChanged();
    partial void OnUpdatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedDateChanged();
    partial void OnUpdatedUserChanging(string value);
    partial void OnUpdatedUserChanged();
    partial void OnMapPathChanging(string value);
    partial void OnMapPathChanged();
    partial void OnPageNumberChanging(System.Nullable<int> value);
    partial void OnPageNumberChanged();
    partial void OnDownloadCountChanging(System.Nullable<int> value);
    partial void OnDownloadCountChanged();
    #endregion
		
		public FileVanBan()
		{
			this._VanBan = default(EntityRef<VanBan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long FileID
		{
			get
			{
				return this._FileID;
			}
			set
			{
				if ((this._FileID != value))
				{
					this.OnFileIDChanging(value);
					this.SendPropertyChanging();
					this._FileID = value;
					this.SendPropertyChanged("FileID");
					this.OnFileIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VanBanID", DbType="Int NOT NULL")]
		public int VanBanID
		{
			get
			{
				return this._VanBanID;
			}
			set
			{
				if ((this._VanBanID != value))
				{
					if (this._VanBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVanBanIDChanging(value);
					this.SendPropertyChanging();
					this._VanBanID = value;
					this.SendPropertyChanged("VanBanID");
					this.OnVanBanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(1000)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileType", DbType="NVarChar(20)")]
		public string FileType
		{
			get
			{
				return this._FileType;
			}
			set
			{
				if ((this._FileType != value))
				{
					this.OnFileTypeChanging(value);
					this.SendPropertyChanging();
					this._FileType = value;
					this.SendPropertyChanged("FileType");
					this.OnFileTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileSize", DbType="BigInt")]
		public System.Nullable<long> FileSize
		{
			get
			{
				return this._FileSize;
			}
			set
			{
				if ((this._FileSize != value))
				{
					this.OnFileSizeChanging(value);
					this.SendPropertyChanging();
					this._FileSize = value;
					this.SendPropertyChanged("FileSize");
					this.OnFileSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientFileName", DbType="NVarChar(2000)")]
		public string ClientFileName
		{
			get
			{
				return this._ClientFileName;
			}
			set
			{
				if ((this._ClientFileName != value))
				{
					this.OnClientFileNameChanging(value);
					this.SendPropertyChanging();
					this._ClientFileName = value;
					this.SendPropertyChanged("ClientFileName");
					this.OnClientFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServerFileName", DbType="NVarChar(1000)")]
		public string ServerFileName
		{
			get
			{
				return this._ServerFileName;
			}
			set
			{
				if ((this._ServerFileName != value))
				{
					this.OnServerFileNameChanging(value);
					this.SendPropertyChanging();
					this._ServerFileName = value;
					this.SendPropertyChanged("ServerFileName");
					this.OnServerFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedDate
		{
			get
			{
				return this._UpdatedDate;
			}
			set
			{
				if ((this._UpdatedDate != value))
				{
					this.OnUpdatedDateChanging(value);
					this.SendPropertyChanging();
					this._UpdatedDate = value;
					this.SendPropertyChanged("UpdatedDate");
					this.OnUpdatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedUser", DbType="NVarChar(1000)")]
		public string UpdatedUser
		{
			get
			{
				return this._UpdatedUser;
			}
			set
			{
				if ((this._UpdatedUser != value))
				{
					this.OnUpdatedUserChanging(value);
					this.SendPropertyChanging();
					this._UpdatedUser = value;
					this.SendPropertyChanged("UpdatedUser");
					this.OnUpdatedUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MapPath", DbType="NVarChar(2000)")]
		public string MapPath
		{
			get
			{
				return this._MapPath;
			}
			set
			{
				if ((this._MapPath != value))
				{
					this.OnMapPathChanging(value);
					this.SendPropertyChanging();
					this._MapPath = value;
					this.SendPropertyChanged("MapPath");
					this.OnMapPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageNumber", DbType="Int")]
		public System.Nullable<int> PageNumber
		{
			get
			{
				return this._PageNumber;
			}
			set
			{
				if ((this._PageNumber != value))
				{
					this.OnPageNumberChanging(value);
					this.SendPropertyChanging();
					this._PageNumber = value;
					this.SendPropertyChanged("PageNumber");
					this.OnPageNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DownloadCount", DbType="Int")]
		public System.Nullable<int> DownloadCount
		{
			get
			{
				return this._DownloadCount;
			}
			set
			{
				if ((this._DownloadCount != value))
				{
					this.OnDownloadCountChanging(value);
					this.SendPropertyChanging();
					this._DownloadCount = value;
					this.SendPropertyChanged("DownloadCount");
					this.OnDownloadCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VanBan_FileVanBan", Storage="_VanBan", ThisKey="VanBanID", OtherKey="VanBanID", IsForeignKey=true)]
		public VanBan VanBan
		{
			get
			{
				return this._VanBan.Entity;
			}
			set
			{
				VanBan previousValue = this._VanBan.Entity;
				if (((previousValue != value) 
							|| (this._VanBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VanBan.Entity = null;
						previousValue.FileVanBans.Remove(this);
					}
					this._VanBan.Entity = value;
					if ((value != null))
					{
						value.FileVanBans.Add(this);
						this._VanBanID = value.VanBanID;
					}
					else
					{
						this._VanBanID = default(int);
					}
					this.SendPropertyChanged("VanBan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VanBan")]
	public partial class VanBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VanBanID;
		
		private string _TieuDe;
		
		private string _TieuDeKhongDau;
		
		private string _SoVanBan;
		
		private string _TomTatNoiDung;
		
		private string _TomTatNoiDungKhongDau;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private string _CreatedUser;
		
		private System.Nullable<System.DateTime> _UpdatedDate;
		
		private string _UpdatedUser;
		
		private System.Nullable<bool> _IsPublish;
		
		private System.Nullable<bool> _GhimLenDau;
		
		private string _Tag;
		
		private System.Nullable<System.DateTime> _PublishDate;
		
		private EntitySet<FileVanBan> _FileVanBans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVanBanIDChanging(int value);
    partial void OnVanBanIDChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnTieuDeKhongDauChanging(string value);
    partial void OnTieuDeKhongDauChanged();
    partial void OnSoVanBanChanging(string value);
    partial void OnSoVanBanChanged();
    partial void OnTomTatNoiDungChanging(string value);
    partial void OnTomTatNoiDungChanged();
    partial void OnTomTatNoiDungKhongDauChanging(string value);
    partial void OnTomTatNoiDungKhongDauChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnCreatedUserChanging(string value);
    partial void OnCreatedUserChanged();
    partial void OnUpdatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedDateChanged();
    partial void OnUpdatedUserChanging(string value);
    partial void OnUpdatedUserChanged();
    partial void OnIsPublishChanging(System.Nullable<bool> value);
    partial void OnIsPublishChanged();
    partial void OnGhimLenDauChanging(System.Nullable<bool> value);
    partial void OnGhimLenDauChanged();
    partial void OnTagChanging(string value);
    partial void OnTagChanged();
    partial void OnPublishDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPublishDateChanged();
    #endregion
		
		public VanBan()
		{
			this._FileVanBans = new EntitySet<FileVanBan>(new Action<FileVanBan>(this.attach_FileVanBans), new Action<FileVanBan>(this.detach_FileVanBans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VanBanID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int VanBanID
		{
			get
			{
				return this._VanBanID;
			}
			set
			{
				if ((this._VanBanID != value))
				{
					this.OnVanBanIDChanging(value);
					this.SendPropertyChanging();
					this._VanBanID = value;
					this.SendPropertyChanged("VanBanID");
					this.OnVanBanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(2000)")]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDeKhongDau", DbType="NVarChar(2000)")]
		public string TieuDeKhongDau
		{
			get
			{
				return this._TieuDeKhongDau;
			}
			set
			{
				if ((this._TieuDeKhongDau != value))
				{
					this.OnTieuDeKhongDauChanging(value);
					this.SendPropertyChanging();
					this._TieuDeKhongDau = value;
					this.SendPropertyChanged("TieuDeKhongDau");
					this.OnTieuDeKhongDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoVanBan", DbType="NVarChar(200)")]
		public string SoVanBan
		{
			get
			{
				return this._SoVanBan;
			}
			set
			{
				if ((this._SoVanBan != value))
				{
					this.OnSoVanBanChanging(value);
					this.SendPropertyChanging();
					this._SoVanBan = value;
					this.SendPropertyChanged("SoVanBan");
					this.OnSoVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TomTatNoiDung", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string TomTatNoiDung
		{
			get
			{
				return this._TomTatNoiDung;
			}
			set
			{
				if ((this._TomTatNoiDung != value))
				{
					this.OnTomTatNoiDungChanging(value);
					this.SendPropertyChanging();
					this._TomTatNoiDung = value;
					this.SendPropertyChanged("TomTatNoiDung");
					this.OnTomTatNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TomTatNoiDungKhongDau", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string TomTatNoiDungKhongDau
		{
			get
			{
				return this._TomTatNoiDungKhongDau;
			}
			set
			{
				if ((this._TomTatNoiDungKhongDau != value))
				{
					this.OnTomTatNoiDungKhongDauChanging(value);
					this.SendPropertyChanging();
					this._TomTatNoiDungKhongDau = value;
					this.SendPropertyChanged("TomTatNoiDungKhongDau");
					this.OnTomTatNoiDungKhongDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedUser", DbType="NVarChar(1000)")]
		public string CreatedUser
		{
			get
			{
				return this._CreatedUser;
			}
			set
			{
				if ((this._CreatedUser != value))
				{
					this.OnCreatedUserChanging(value);
					this.SendPropertyChanging();
					this._CreatedUser = value;
					this.SendPropertyChanged("CreatedUser");
					this.OnCreatedUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedDate
		{
			get
			{
				return this._UpdatedDate;
			}
			set
			{
				if ((this._UpdatedDate != value))
				{
					this.OnUpdatedDateChanging(value);
					this.SendPropertyChanging();
					this._UpdatedDate = value;
					this.SendPropertyChanged("UpdatedDate");
					this.OnUpdatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedUser", DbType="NVarChar(1000)")]
		public string UpdatedUser
		{
			get
			{
				return this._UpdatedUser;
			}
			set
			{
				if ((this._UpdatedUser != value))
				{
					this.OnUpdatedUserChanging(value);
					this.SendPropertyChanging();
					this._UpdatedUser = value;
					this.SendPropertyChanged("UpdatedUser");
					this.OnUpdatedUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublish", DbType="Bit")]
		public System.Nullable<bool> IsPublish
		{
			get
			{
				return this._IsPublish;
			}
			set
			{
				if ((this._IsPublish != value))
				{
					this.OnIsPublishChanging(value);
					this.SendPropertyChanging();
					this._IsPublish = value;
					this.SendPropertyChanged("IsPublish");
					this.OnIsPublishChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhimLenDau", DbType="Bit")]
		public System.Nullable<bool> GhimLenDau
		{
			get
			{
				return this._GhimLenDau;
			}
			set
			{
				if ((this._GhimLenDau != value))
				{
					this.OnGhimLenDauChanging(value);
					this.SendPropertyChanging();
					this._GhimLenDau = value;
					this.SendPropertyChanged("GhimLenDau");
					this.OnGhimLenDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tag", DbType="NVarChar(1000)")]
		public string Tag
		{
			get
			{
				return this._Tag;
			}
			set
			{
				if ((this._Tag != value))
				{
					this.OnTagChanging(value);
					this.SendPropertyChanging();
					this._Tag = value;
					this.SendPropertyChanged("Tag");
					this.OnTagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PublishDate
		{
			get
			{
				return this._PublishDate;
			}
			set
			{
				if ((this._PublishDate != value))
				{
					this.OnPublishDateChanging(value);
					this.SendPropertyChanging();
					this._PublishDate = value;
					this.SendPropertyChanged("PublishDate");
					this.OnPublishDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VanBan_FileVanBan", Storage="_FileVanBans", ThisKey="VanBanID", OtherKey="VanBanID")]
		public EntitySet<FileVanBan> FileVanBans
		{
			get
			{
				return this._FileVanBans;
			}
			set
			{
				this._FileVanBans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FileVanBans(FileVanBan entity)
		{
			this.SendPropertyChanging();
			entity.VanBan = this;
		}
		
		private void detach_FileVanBans(FileVanBan entity)
		{
			this.SendPropertyChanging();
			entity.VanBan = null;
		}
	}
}
#pragma warning restore 1591
